from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from src.models.candidate import CandidateProfileExt, QuestionMemory, AuditTrail

class AutoFillEngine:
    def __init__(self, db: AsyncSession):
        self.db = db

    async def _lookup_memory(self, question: str):
        normalized = question.lower().strip()
        result = await self.db.execute(
            select(QuestionMemory).where(QuestionMemory.normalized_question == normalized)
        )
        return result.scalar_one_or_none()

    async def get_answer(self, question: str, question_type: str, application_id: int, profile: CandidateProfileExt):
        # 1. Check Memory
        memory = await self._lookup_memory(question)
        if memory:
            await self._record_audit(application_id, question, memory.answer, memory.source, False)
            return memory.answer

        # 2. Generate new based on type
        answer = None
        source = None
        generated = False

        if question_type == "FACTUAL":
            if "first name" in question.lower() and profile:
                answer = profile.first_name
            elif "last name" in question.lower() and profile:
                answer = profile.last_name
            elif "email" in question.lower() and profile:
                answer = profile.email
            else:
                return "[USER_INPUT_REQUIRED]"
            source = "USER"

        elif question_type == "PROFILE-DERIVED":
            if "experience" in question.lower() and profile and profile.employment:
                answer = f"I have worked at {profile.employment[0].company} as {profile.employment[0].title}."
            source = "CV"

        elif question_type == "ESSAY":
            # Mock Gemini generation
            answer = f"[Generated by Gemini based on profile] I am interested in this role because my background aligns with it."
            source = "GENERATED"
            generated = True

        if answer:
            # Save to memory
            mem = QuestionMemory(
                question=question,
                normalized_question=question.lower().strip(),
                answer=answer,
                answer_type=question_type,
                source=source
            )
            self.db.add(mem)
            await self._record_audit(application_id, question, answer, source, generated)

        return answer

    async def _record_audit(self, app_id: int, question: str, answer: str, source: str, generated: bool):
        audit = AuditTrail(
            application_id=app_id,
            question=question,
            answer=answer,
            source=source,
            generated=generated
        )
        self.db.add(audit)
