"""baseline schema (pre-alembic create_all)

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-09-29 19:38:53.753352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=512), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('application_url', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('company', sa.String(length=256), nullable=True),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('work_mode', sa.Enum('REMOTE', 'ONSITE', 'HYBRID', 'UNKNOWN', name='workmode'), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('preferred_qualifications', sa.Text(), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(length=16), nullable=True),
    sa.Column('compensation_text', sa.Text(), nullable=True),
    sa.Column('pay_status', sa.Enum('PAID', 'UNPAID', 'UNKNOWN', name='paystatus'), nullable=True),
    sa.Column('pay_evidence', sa.Text(), nullable=True),
    sa.Column('posted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ats_platform', sa.String(length=128), nullable=True),
    sa.Column('company_info', sa.Text(), nullable=True),
    sa.Column('posting_snapshot', sa.Text(), nullable=True),
    sa.Column('classification_category', sa.String(length=64), nullable=True),
    sa.Column('classification_evidence', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('dedup_hash', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('classification_status', sa.String(length=32), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_company'), ['company'], unique=False)
        batch_op.create_index('ix_jobs_company_title', ['company', 'title'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_dedup_hash'), ['dedup_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_jobs_source'), ['source'], unique=False)
        batch_op.create_index('ix_jobs_source_source_id', ['source', 'source_id'], unique=False)

    op.create_table('vault_identity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('middle_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('preferred_name', sa.String(length=128), nullable=True),
    sa.Column('pronouns', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('linkedin_url', sa.String(length=256), nullable=True),
    sa.Column('github_url', sa.String(length=256), nullable=True),
    sa.Column('portfolio_url', sa.String(length=256), nullable=True),
    sa.Column('codeforces_url', sa.String(length=256), nullable=True),
    sa.Column('leetcode_url', sa.String(length=256), nullable=True),
    sa.Column('kaggle_url', sa.String(length=256), nullable=True),
    sa.Column('google_scholar_url', sa.String(length=256), nullable=True),
    sa.Column('other_links', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('DISCOVERED', 'QUEUED', 'IN_PROGRESS', 'SUBMITTED', 'ASSESSMENT', 'INTERVIEW', 'REJECTED', 'OFFER', 'FAILED', 'CLOSED', name='applicationstatus'), nullable=False),
    sa.Column('application_url', sa.Text(), nullable=True),
    sa.Column('date_discovered', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_queued', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_applied', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resume_used', sa.Text(), nullable=True),
    sa.Column('cover_letter_used', sa.Text(), nullable=True),
    sa.Column('answers_submitted', sa.JSON(), nullable=True),
    sa.Column('other_materials', sa.JSON(), nullable=True),
    sa.Column('confirmation_id', sa.String(length=256), nullable=True),
    sa.Column('confirmation_text', sa.Text(), nullable=True),
    sa.Column('confirmation_screenshot', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('posting_snapshot_at_apply', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)

    op.create_table('vault_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('canonical_key', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('sensitivity', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['vault_identity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vault_answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vault_answer_canonical_key'), ['canonical_key'], unique=False)

    op.create_table('vault_education',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('institution', sa.String(length=256), nullable=True),
    sa.Column('degree', sa.String(length=128), nullable=True),
    sa.Column('major', sa.String(length=128), nullable=True),
    sa.Column('minor', sa.String(length=128), nullable=True),
    sa.Column('start_date', sa.String(length=64), nullable=True),
    sa.Column('end_date', sa.String(length=64), nullable=True),
    sa.Column('cgpa', sa.String(length=64), nullable=True),
    sa.Column('scale', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['vault_identity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vault_employment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=256), nullable=True),
    sa.Column('job_title', sa.String(length=256), nullable=True),
    sa.Column('employment_type', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.String(length=64), nullable=True),
    sa.Column('end_date', sa.String(length=64), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['vault_identity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vault_project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technologies', sa.Text(), nullable=True),
    sa.Column('github_url', sa.Text(), nullable=True),
    sa.Column('demo_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['vault_identity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vault_resume',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=256), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['vault_identity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vault_skill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['vault_identity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_intelligence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('role_summary', sa.Text(), nullable=True),
    sa.Column('company_summary', sa.Text(), nullable=True),
    sa.Column('inferred_topics', sa.JSON(), nullable=True),
    sa.Column('generated_questions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_intelligence')
    op.drop_table('vault_skill')
    op.drop_table('vault_resume')
    op.drop_table('vault_project')
    op.drop_table('vault_employment')
    op.drop_table('vault_education')
    with op.batch_alter_table('vault_answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vault_answer_canonical_key'))

    op.drop_table('vault_answer')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_job_id'))

    op.drop_table('applications')
    op.drop_table('vault_identity')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_source_source_id')
        batch_op.drop_index(batch_op.f('ix_jobs_source'))
        batch_op.drop_index(batch_op.f('ix_jobs_dedup_hash'))
        batch_op.drop_index('ix_jobs_company_title')
        batch_op.drop_index(batch_op.f('ix_jobs_company'))

    op.drop_table('jobs')
    # ### end Alembic commands ###
