"""companies, job_sightings, job enrichment columns

Revision ID: 0003_companies_sightings
Revises: 0002_location_fit
Create Date: 2026-09-29 19:47:22.168063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_companies_sightings'
down_revision: Union[str, Sequence[str], None] = '0002_location_fit'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('normalized_name', sa.String(length=256), nullable=False),
    sa.Column('domain', sa.String(length=256), nullable=True),
    sa.Column('careers_url', sa.Text(), nullable=True),
    sa.Column('ats_type', sa.String(length=32), nullable=False),
    sa.Column('ats_token', sa.String(length=256), nullable=True),
    sa.Column('is_india', sa.Boolean(), nullable=False),
    sa.Column('india_cities', sa.JSON(), nullable=True),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('funding', sa.String(length=128), nullable=True),
    sa.Column('discovered_via', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('about_text', sa.Text(), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_job_count', sa.Integer(), nullable=True),
    sa.Column('crawl_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_normalized_name'), ['normalized_name'], unique=True)

    op.create_table('job_sightings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='fk_job_sightings_job_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'source', 'source_url', name='uq_job_sightings')
    )
    with op.batch_alter_table('job_sightings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_sightings_job_id'), ['job_id'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('stipend_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stipend_max', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stipend_currency', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('stipend_period', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('duration_months', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('role_family', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('apply_channel', sa.String(length=24), nullable=True))
        batch_op.create_index(batch_op.f('ix_jobs_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_role_family'), ['role_family'], unique=False)
        batch_op.create_foreign_key('fk_jobs_company_id', 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_jobs_company_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_jobs_role_family'))
        batch_op.drop_index(batch_op.f('ix_jobs_company_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_city'))
        batch_op.drop_column('apply_channel')
        batch_op.drop_column('role_family')
        batch_op.drop_column('start_date')
        batch_op.drop_column('duration_months')
        batch_op.drop_column('stipend_period')
        batch_op.drop_column('stipend_currency')
        batch_op.drop_column('stipend_max')
        batch_op.drop_column('stipend_min')
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('job_sightings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_sightings_job_id'))

    op.drop_table('job_sightings')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_normalized_name'))

    op.drop_table('companies')
    # ### end Alembic commands ###
